#!/usr/bin/env ruby

require 'optparse'
require 'logger'
require 'colorize'
require_relative 'hiera'


SEVERITY_MAP = {
  "DEBUG" => "DBUG",
  "INFO" => "INFO".blue,
  "WARN" => "WARN".yellow,
  "ERROR" => "ERRO".red,
  "FATAL" => "FATE".on_red,
  "UNKNOWN" => "UNKN",
}

options = {
  action: :add_classes
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: mover.rb -h host [options] class [...]"
  opts.on("-R", "--remove", "Remove classes from node(s) (default id to add)") { options[:action] = :remove_classes }
  opts.on("-h", "--host HOSTS", "Hostnames to process (comma-separated)") { |hosts| options[:host] = hosts.split(',') }
  opts.on("-D", "--apply", "Apply changes, overvise it's dry run") { options[:apply] = true }
  opts.on("-d", "--debug", "Print debug info") { options[:debug] = true }
end

parser.parse!

(puts parser; exit 0) unless options[:host] and ARGV.size != 0

LOG = Logger.new STDOUT
LOG.level = options[:debug] ? Logger::DEBUG : Logger::INFO
LOG.formatter = proc do |severity, datetime, progname, msg|
  "#{SEVERITY_MAP[severity]}: [#{progname}] #{msg}\n"
end

options[:host].each do |host|
  Hiera.public_send options[:action], host, ARGV, options[:apply]
end